defaults:
  - datamodule: imagenet32
  - model: dtp
  - network: simple_vgg
  - trainer: default
  - reproduce: null

# meta experiment info
seed: 123
debug: False
data_dir: /home/amoudgl/Projects/data  # absolute path to datasets directory