# CIFAR-10 defaults
# checkout README or conf/reproduce directory for good defaults for other dataset + model configurations
_target_: target_prop.models.LayerParallelDTP
hparams:
  use_scheduler: True
  feedback_training_iterations: [20, 30, 35, 55, 20]
  noise: [0.4, 0.4, 0.2, 0.2, 0.08]
  beta: 0.7
  feedback_samples_per_iteration: 1
  early_stopping_patience: 0
  init_symetric_weights: False
  plot_every: 10000

  f_optim:
    _target_: torch.optim.SGD
    lr: 0.08
    weight_decay: 1e-4
    momentum: 0.9

  b_optim:
    _target_: torch.optim.SGD
    # specify learning rate for each layer
    # list order: input to output layer
    lr: [1e-4, 3.5e-4, 8e-3, 8e-3, 0.18]
    weight_decay: 0
    momentum: 0.9
