_target_: target_prop.datasets.CIFAR10DataModule
batch_size: 128
num_workers: 16
pin_memory: True
shuffle: True

# train transforms
train_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomCrop
      size: 32
      padding: 4
      padding_mode: "edge"
    - _target_: torchvision.transforms.ToTensor
    - _target_: target_prop.datasets.cifar10_normalization
val_transforms:  # same as train tranforms
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomCrop
      size: 32
      padding: 4
      padding_mode: "edge"
    - _target_: torchvision.transforms.ToTensor
    - _target_: target_prop.datasets.cifar10_normalization
test_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: target_prop.datasets.cifar10_normalization
